This was not exactly a *tmp* file + minor changes in output messages

diff --git a/resolve-containers b/resolve-containers
--- a/resolve-containers
+++ b/resolve-containers
@@ -1,10 +1,10 @@
 #!/bin/bash
 SELF_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 APP_NAME=$(basename "$SELF_DIR")
-APP_TMPFILE="/var/tmp/slarp"
+APP_VARFILE="/var/slarp"
 
-function abort_tmp {
-	echo "Error: tmp file absent or corrupted. Please restart $APP_NAME." >&2
+function abort_varfile {
+	echo "Error: $APP_VARFILE absent or corrupted - please restart $APP_NAME" >&2
 	exit 1
 }
 
@@ -13,8 +13,8 @@ function abort_tmp {
 	exit 1
 }
 
-source "$APP_TMPFILE" || abort_tmp
-[ -z "$VHOSTS_DIR" ] && abort_tmp
+source "$APP_VARFILE" || abort_varfile
+[ -z "$VHOSTS_DIR" ] && abort_varfile
 cd "$VHOSTS_DIR"
 
 vhostsSection="#APACHE VHOSTS"
@@ -62,4 +62,4 @@ done < <(docker exec $APP_NAME cat /etc/hosts)
 newHostsFileContent="$newHostsFileContent
 $vhostsSection"
 docker exec $APP_NAME bash -c "echo \"$newHostsFileContent\" > /etc/hosts"
-echo "Updated hosts file"
+echo "Updated container's hosts file"
diff --git a/start b/start
--- a/start
+++ b/start
@@ -1,10 +1,10 @@
 #!/bin/bash
 SELF_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 APP_NAME=$(basename "$SELF_DIR")
-APP_TMPFILE="/var/tmp/slarp"
+APP_VARFILE="/var/slarp"
 
 [ $(. "$SELF_DIR"/is-running) == "no" ] || {
-	echo "$APP_NAME is already running!"
+	echo "$APP_NAME is already running"
 	exit
 }
 
@@ -15,18 +15,18 @@ APP_TMPFILE="/var/tmp/slarp"
 
 for dir in "$CERTS_DIR" "$VHOSTS_DIR" "$APACHE_LOGS_DIR" "$CERTBOT_LOGS_DIR"; do
 	mkdir -p "$dir" || {
-		echo "Could not create $dir. Aborting." >&2
+		echo "Could not create $dir - aborting" >&2
 		exit 74
 	}
 done
 
-echo CERTS_DIR="$CERTS_DIR"               >  "$APP_TMPFILE" || {
-	echo "Could not write $APP_TMPFILE. Aborting." >&2
+echo CERTS_DIR="$CERTS_DIR"               >  "$APP_VARFILE" || {
+	echo "Could not write $APP_VARFILE - aborting" >&2
 	exit 74
 }
-echo VHOSTS_DIR="$VHOSTS_DIR"             >> "$APP_TMPFILE"
-echo APACHE_LOGS_DIR="$APACHE_LOGS_DIR"   >> "$APP_TMPFILE"
-echo CERTBOT_LOGS_DIR="$CERTBOT_LOGS_DIR" >> "$APP_TMPFILE"
+echo VHOSTS_DIR="$VHOSTS_DIR"             >> "$APP_VARFILE"
+echo APACHE_LOGS_DIR="$APACHE_LOGS_DIR"   >> "$APP_VARFILE"
+echo CERTBOT_LOGS_DIR="$CERTBOT_LOGS_DIR" >> "$APP_VARFILE"
 
 docker run -d --restart on-failure \
            --name $APP_NAME \
