WIP managing directories

diff --git a/start b/start
--- a/start
+++ b/start
@@ -12,10 +12,17 @@ DEFAULT_VHOSTS_DIR="$SELF_DIR"vhosts/
 DEFAULT_APACHE_LOGS_DIR="$SELF_DIR"apache-logs/
 DEFAULT_CERTBOT_LOGS_DIR="$SELF_DIR"certbot-logs/
 
-CERTS_DIR=DEFAULT_CERTS_DIR
-VHOSTS_DIR=DEFAULT_VHOSTS_DIR
-APACHE_LOGS_DIR=DEFAULT_APACHE_LOGS_DIR
-CERTBOT_LOGS_DIR=DEFAULT_CERTBOT_LOGS_DIR
+[ -z "$CERTS_DIR" ] && CERTS_DIR="$DEFAULT_CERTS_DIR"
+[ -z "$VHOSTS_DIR" ] && VHOSTS_DIR="$DEFAULT_VHOSTS_DIR"
+[ -z "$APACHE_LOGS_DIR" ] && APACHE_LOGS_DIR="$DEFAULT_APACHE_LOGS_DIR"
+[ -z "$CERTBOT_LOGS_DIR" ] && CERTBOT_LOGS_DIR="$DEFAULT_CERTBOT_LOGS_DIR"
+
+for dir in "$CERTS_DIR" "$VHOSTS_DIR" "$APACHE_LOGS_DIR" "$CERTBOT_LOGS_DIR"; do
+	mkdir -p "$dir" || {
+		echo "Could not create $dir. Aborting." >&2
+		exit 74
+	}
+done
 
 docker run -d --restart on-failure\
            --name $APP_NAME\
